if (typeof translations === 'undefined') window.translations = { en: {}, fr: {} };
        /* English fallback so the page renders even if translations.js is missing */
        const FB = {
            hero_desc: 'I write code the way I like to solve problems: patiently, thoughtfully, and with care. Whether it is making something work behind the scenes or making it feel simple on the outside, I put my heart into every part of the process.',
            hero_subtitle: 'Software Engineering Student @ ENSA Oujda | AI & DevOps Enthusiast',
            exp_item1_date: '07/2026 - 09/2026', exp_item1_title: 'Software Engineering Intern', exp_item1_org: 'Digitalia Solutions — Casablanca',
            exp_item1_desc: '<li>Built Targetalent: an AI-powered talent sourcing platform combining LangGraph agents, Spring Boot and React 19.</li>',
            exp_item2_date: '07/2025 - 08/2025', exp_item2_title: 'Software Engineering Intern', exp_item2_org: 'AMEE — Rabat',
            exp_item2_desc: '<li>Built an HR leave management portal with automated workflows and real-time dashboards.</li>',
            vol_item1_org: 'Oriental Science House', vol_item1_title: 'Mentor & Workshop Animator',
            vol_item1_desc: '<li>Facilitated workshops in AI, Deep Learning and n8n automation.</li><li>Built physical models to explain complex science to younger learners.</li>',
            vol_item2_org: 'Club GI ENSAO', vol_item2_title: 'Technical Organization',
            vol_item2_desc: '<li>Coordinated large events and technical competitions.</li><li>Mentored junior students through technical challenges.</li>',
            edu_item1_date: '2021 - 2027 (Expected)', edu_item1_title: 'Engineering Degree in Computer Science (AI Option)', edu_item1_org: 'National School of Applied Sciences - Oujda (ENSAO)',
            edu_item1_desc: '<li>Software Engineering, Artificial Intelligence and Distributed Systems.</li><li>Currently in 4th year.</li>',
            edu_item2_date: '2020 - 2021', edu_item2_title: 'High School Diploma in Mathematical Sciences A', edu_item2_org: 'Hassan Ibn Tabit High School - Zaio',
            edu_item2_desc: '<li>Graduated with Honors.</li><li>Focus on advanced mathematics and physics.</li>',
            proj_targetalent_title: 'Targetalent · AI Talent Sourcing', proj_targetalent_desc: 'AI-powered recruitment platform turning natural-language queries into ranked candidate shortlists.',
            proj_cdg_capital_title: 'CDG Capital · Financial AI', proj_cdg_capital_desc: 'Automated analysis of Moroccan PCGE financial statements with Generative AI.',
            proj_miathon_title: 'SANAD · Companion Robot', proj_miathon_desc: 'Web dashboard simulating the SANAD companion robot for elderly Moroccans, built during the MIATHON\'03 Hackathon.',
            proj_afriqai_title: 'AfriqAI · Feedback Analyzer', proj_afriqai_desc: 'AI microservice for real-time feedback analysis inside the AfriqAI platform.',
            proj_chatbot_title: 'Chatbot MSO · Gov Assistant', proj_chatbot_desc: 'Multilingual RAG chatbot for Moroccan administrative procedures.',
            proj1_title: 'Jira Clone · Task Management', proj1_desc: 'Robust back-end for real-time task management with a RESTful API.',
            stockify_title: 'Stockify · Inventory Hub', stockify_desc: 'Real-time stock tracking with automated alerts, built on Symfony 7.',
            proj3_title: 'Soukify · Artisan Marketplace', proj3_desc: 'Android marketplace connecting Moroccan artisans with buyers.',
            proj_quiz_title: 'Tech Quiz Pro · IT Learning', proj_quiz_desc: 'Android quiz app with 8 technical tracks and 350+ challenges.',
            proj4_title: 'Vision Engine · Motion Detection', proj4_desc: 'Real-time motion detection with OpenCV and Streamlit.',
            proj5_title: 'QueryPix · CBIR Image Search', proj5_desc: 'Content-based image retrieval on the Corel-1000 dataset.',
            proj_amee_title: 'eCongé AMEE · HR Management', proj_amee_desc: 'Full-stack PHP/MySQL portal for leave tracking and HR documents.',
            proj6_title: 'Shifaa · Healthcare Hub', proj6_desc: 'JavaFX desktop suite for patients, doctors and treatments.',
            proj7_title: 'Bayt Al Hikma · Library System', proj7_desc: 'Library engine with web, desktop and CLI interfaces.',
            proj_portfolio_title: 'Digital Portfolio · Web Showcase', proj_portfolio_desc: 'Multilingual portfolio built with vanilla JS.',
            proj_btn_details: 'See Details', proj_source: 'Source', proj_coming_soon: 'Coming soon', proj_vision_title: 'Project Vision', proj_features_title: 'Core Features', proj_blueprint_title: 'Technical Blueprint', resume_download: 'Download', proj_challenge: 'Challenge:', proj_solution: 'Solution:', view_case: 'View case study',
            proj_targetalent_sol: 'LangGraph agentic pipeline with Llama 3.3, MCP tools, hybrid scoring (skills/exp/location/embeddings) and pgvector for semantic search.',
            proj_cdg_capital_sol: 'FastAPI backend with pdfplumber and Claude to parse dense PDF reports, plus a React dashboard.',
            proj_afriqai_sol: 'FastAPI microservice, plus ongoing maintenance of the Spring Boot core.',
            proj_chatbot_sol: 'FastAPI + Vite engine with Hugging Face LLMs, local vector storage and Tesseract OCR.',
            proj_miathon_sol: 'Modular React dashboard simulating a Darija voice interface, OCR and safety alerts.',
            proj_jira_sol: 'Spring Boot REST API with role-based auth, WebSocket real-time sync and a React front-end.',
            stockify_sol: 'Symfony 7 and Doctrine power a sub-second analytics pipeline with automated low-stock alerts.',
            proj3_sol: 'Android SDK and Firebase, structured with the MVVM pattern for clean separation of concerns.',
            proj_quiz_sol: 'Android Room database powers offline quiz sessions with adaptive scoring across 8 tech tracks.',
            proj_vision_sol: 'OpenCV motion pipeline with frame differencing and contour detection, visualised via Streamlit.',
            proj_querypix_sol: 'Histogram and texture descriptors ranked by cosine similarity on the Corel-1000 dataset.',
            proj_amee_sol: 'PHP/MySQL portal with role-based leave workflows, real-time HR dashboards and automated PDF export.',
            proj_shifaa_sol: 'JavaFX 21 MVC with multi-user roles, OpenPDF reporting and a fully relational MySQL backend.',
            proj_bayt_sol: 'Python + Streamlit UI with a Pandas data layer and dual web/CLI interfaces for library management.',
            proj_portfolio_sol: 'Modular vanilla JS with partial HTML loading, i18n, dark mode, EmailJS and a custom animation engine.',
            stat_projects: '12+ Engineering Projects', stat_techs: '15+ Tools', stat_certs: '9 Certifications', stat_intern: '2 Internships',
            tech_cat_lan: 'Languages', tech_cat_fw: 'Frameworks', tech_cat_db: 'Databases', tech_cat_ai: 'AI & Data', tech_cat_sys_net: 'Systems & Networks', tech_cat4: 'Tools & IDEs', tech_cat7: 'Agile', tech_cat3: 'Soft skills', lang_label: 'Languages',
            soft_agile: 'Agile', soft_scrum: 'Scrum', soft_jira: 'Jira', soft_communication: 'Communication', soft_teamwork: 'Teamwork', soft_problem_solving: 'Problem Solving', soft_adaptability: 'Adaptability',
            lang_arabic: 'Arabic (Native)', lang_french: 'French (B2)', lang_english: 'English (C1)',
            cert_agentic_title: 'Agentic Workflows', cert_java_inter_title: 'Java Intermediate', cert5_title: 'Prompt Engineering', cert_docker_title: 'Docker Essentials', cert_junit_title: 'JUnit Essentials',
            cert3_title: 'DevOps 101', cert1_title: 'Relational Database', cert4_title: 'SQL Intermediate', cert2_title: 'Java (Basic)',
            cert_agentic_desc: '', cert_java_inter_desc: '', cert5_desc: '', cert_docker_desc: '', cert_junit_desc: '', cert3_desc: '', cert1_desc: '', cert4_desc: '', cert2_desc: '',
            gallery_n8n_title: 'n8n Workflows', gallery_n8n_desc: '', gallery_events_title: 'Events Gallery', gallery_events_desc: '', gallery_cert_title: 'Volunteer Certificates', gallery_cert_desc: '', exp_btn_cert: 'View Certificate'
        };
        const A = 'assets/images/Apps/';
        /* [id, category, image, [titleKey, descKey], tech tags, source url] */
        const PROJECTS = [
            ['targetalent', 'web', A + 'Targetalent/targetalent.png', ['proj_targetalent_title', 'proj_targetalent_desc'], ['React 19', 'Spring Boot', 'LangGraph', 'FastAPI', 'pgvector'], 'https://github.com/SalmasKit/targetalent'],
            ['afriqai', 'web', A + 'FeedbackAnalyzer/FeedbackAnalyzer.png', ['proj_afriqai_title', 'proj_afriqai_desc'], ['Spring Boot', 'FastAPI', 'Generative AI'], 'https://gitlab.com/pfa353013'],
            ['jira', 'web', A + 'Jira/jira_clone.png', ['proj1_title', 'proj1_desc'], ['Spring Boot', 'React', 'PostgreSQL'], 'https://gitlab.com/formations2026/gera-back'],
            ['stockify', 'web', A + 'Stockify/Stockify.png', ['stockify_title', 'stockify_desc'], ['Symfony 7', 'PHP 8.2', 'MySQL'], 'https://github.com/SalmasKit/StockifyApp'],
            ['cdg', 'web', A + 'CDG/cdg.png', ['proj_cdg_capital_title', 'proj_cdg_capital_desc'], ['FastAPI', 'React', 'Generative AI'], 'https://github.com/SalmasKit/cdgc-financial-assistant'],
            ['chatbot', 'ai', A + 'Chatbotmso/chatbot_mso.png', ['proj_chatbot_title', 'proj_chatbot_desc'], ['FastAPI', 'Vite', 'Hugging Face'], 'https://gitlab.com/chatbot-mso/Chatbot-mso'],
            ['sanad', 'ai', A + 'Sanad/sanad_cover.png', ['proj_miathon_title', 'proj_miathon_desc'], ['FastAPI', 'React', 'Whisper'], 'https://github.com/SalmasKit/sanad-elderly-helper'],
            ['soukify', 'mobile', A + 'Soukify/Soukify.jpeg', ['proj3_title', 'proj3_desc'], ['Android', 'Java', 'Firebase'], 'https://github.com/SalmasKit/SoukifyApp'],
            ['quiz', 'mobile', A + 'Quiz/quiz.jpeg', ['proj_quiz_title', 'proj_quiz_desc'], ['Android', 'Java', 'Room DB'], 'https://github.com/SalmasKit/QuizApp'],
            ['vision', 'ai', A + 'Mouvementdetection/MouvementDetection.png', ['proj4_title', 'proj4_desc'], ['Python', 'OpenCV', 'NumPy'], 'https://github.com/SalmasKit/MotionDetectionApp'],
            ['querypix', 'ai', A + 'Cbir/Cbir.png', ['proj5_title', 'proj5_desc'], ['Scikit-learn', 'Pandas', 'NumPy'], 'https://github.com/SalmasKit/QueryPix-CBIRApp'],
            ['amee', 'web', A + 'Econgeamee/3.png', ['proj_amee_title', 'proj_amee_desc'], ['PHP', 'MySQL', 'JavaScript'], null],
            ['shifaa', 'desktop', A + 'Shifaa/Shifaa.png', ['proj6_title', 'proj6_desc'], ['JavaFX 21', 'MySQL', 'OpenPDF'], 'https://github.com/SalmasKit/ShifaaApp'],
            ['bayt', 'desktop', A + 'Baytalhikma/bayt_al_hikma.png', ['proj7_title', 'proj7_desc'], ['Python', 'Streamlit', 'Pandas'], 'https://github.com/SalmasKit/libraryBaytAlHikmaApp']
        ];
        const STACK = [
            ['tech_cat_lan', ['Java', 'Python', 'JavaScript', 'HTML5/CSS3', 'PHP', 'C#']],
            ['tech_cat_fw', ['Spring Boot', 'React.js', 'FastAPI', 'Symfony', 'Android SDK', 'LangGraph', 'FastMCP', 'Vite', 'JavaEE', 'JavaFX']],
            ['tech_cat_db', ['PostgreSQL', 'MySQL', 'SQLite', 'pgvector', 'Firebase', 'Room']],
            ['tech_cat_ai', ['Machine Learning', 'Generative AI', 'Deep Learning', 'Hugging Face', 'Scikit-learn', 'Pandas/NumPy', 'Computer Vision', 'Whisper']],
            ['tech_cat_sys_net', ['Docker', 'Linux (Ubuntu, Debian)', 'Systems Administration', 'Virtual Machines', 'Network Basics']],
            ['tech_cat4', ['Git / GitHub / GitLab', 'JetBrains / VS Code', 'Docker', 'Postman', 'Bruno', 'JUnit', 'Mockito', 'SonarQube Cloud', 'n8n', 'Android Studio', 'Jupyter / Colab', 'JaCoCo', 'UML', 'Merise', 'Figma', 'Canva']],
            ['tech_cat7', ['@soft_agile', '@soft_scrum', '@soft_jira']],
            ['tech_cat3', ['@soft_communication', '@soft_teamwork', '@soft_problem_solving', '@soft_adaptability']],
            ['lang_label', ['@lang_arabic', '@lang_french', '@lang_english']]
        ];
        const CERTS = [
            ['cert_agentic_title', 'Sololearn', 'Apr 2026', 'Agentic Workflows.pdf', 'fas fa-robot', 'CC-HSWFG6Z7', 'ai'],
            ['cert_java_inter_title', 'Sololearn', 'Apr 2026', 'Java Intermediate.pdf', 'fab fa-java', 'CC-KWY8R7QD', 'dev'],
            ['cert5_title', 'Sololearn', 'Apr 2026', 'PromptEngineering.pdf', 'fas fa-brain', 'CC-SVM1YAQD', 'ai'],
            ['cert_docker_title', 'Simplilearn', 'Mar 2026', 'DockerCertificate.pdf', 'fab fa-docker', '10024321', 'infra'],
            ['cert_junit_title', 'Simplilearn', 'Apr 2026', 'JUnit.pdf', 'fas fa-vial', '10152757', 'testing'],
            ['cert3_title', 'Simplilearn', 'Mar 2026', 'DevOps 101.pdf', 'fas fa-server', '9936127', 'infra'],
            ['cert1_title', 'freeCodeCamp', 'Mar 2026', 'relational-databases-v9.pdf', 'fas fa-database', 'fcc-ad52db15-a244-49e1-a870-b86928a540ac-rdv9', 'db'],
            ['cert4_title', 'HackerRank', 'Mar 2026', 'sql_intermediate certificate.pdf', 'fas fa-table', 'IDC2DDC0F680B9', 'db'],
            ['cert2_title', 'HackerRank', 'Mar 2026', 'java_basic_certificate.pdf', 'fas fa-laptop-code', 'D1EFFDE4738E', 'dev']
        ];
        /* detail pages: translation prefix, demo video, screenshot folder + files */
        const rng = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => a + i);
        const DET = {
            targetalent: { k: 'proj_targetalent', v: 'Baytalhikma/TargetlantDemo.mp4' },
            cdg: { k: 'proj_cdg_capital', v: 'CDG/CDGCapital_FinancialAssistant.mp4' },
            sanad: { k: 'proj_miathon', b: 'Sanad', i: [...rng(369, 376), ...rng(378, 381)].map(n => `Screenshot (${n}).png`) },
            afriqai: { k: 'proj_afriqai', v: 'FeedbackAnalyzer/FeedbackAnalyzer.mp4' },
            chatbot: { k: 'proj_chatbot' }, jira: { k: 'proj1' },
            stockify: { k: 'stockify', v: 'Stockify/STOCKIFY DEMO.mp4' },
            soukify: { k: 'soukify', v: 'Soukify/SOUKIFY%20Demo.mp4' },
            quiz: { k: 'proj_quiz', v: 'Quiz/QUIZAPPDEMO.mp4' },
            vision: { k: 'proj4', v: 'Mouvementdetection/MOTIONDETECTIONDEMO.mp4' },
            querypix: { k: 'proj5', v: 'Cbir/CBIRDEMO.mp4' },
            amee: { k: 'proj_amee', b: 'Econgeamee', i: [...rng(1, 9).map(n => n + '.png'), '10-1.png', ...rng(10, 15).map(n => n + '.png')] },
            shifaa: { k: 'proj6', v: 'Shifaa/SHIFAADEMO.mp4' },
            bayt: { k: 'proj7', v: 'Baytalhikma/BAYTALHIKMADEMO.mp4' }
        };
